### ISSUE TITLE
Test - Unhandled Exceptions

### ISSUE THREAD

**Issue by geramg** [JavierRLomas/NCTaskManager#1]
Use try/catch blocks to avoid main to crash in runtime

**Comment by JavierRLomas** [comment]
Same use in method setRadius() 

public Circle (int r) {
        try {
            if (r < 0) {
                throw new IllegalArgumentException();
            } else {
                radius = r;
            }
        }
        catch (Exception e) {
            System.out.println("Radius must be a number, integer and positive");
        }
    }
